name: Deploy CI

on:
  push:
    branches: [ "deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install software
      run: |
        sudo apt update
        sudo apt install npm leiningen wget
    - name: Install Google Chrome
      run: |
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
        sudo apt update
        sudo apt install google-chrome-stable=92.0.4515.159-1
    - name: Install Chromedriver
      run: |
        wget https://chromedriver.storage.googleapis.com/92.0.4515.107/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        rm chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown $(whoami) /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
    - name: Install node_modules
      run: npm install
    - name: Install dependencies
      run: lein deps
    - name: Run unit tests
      run: lein unit-tests
    - name: Run integration tests
      run: |
        export TEST_CHROME_BINARY=$(which google-chrome)
        export TEST_CHROMEDRIVER_BINARY=/usr/bin/chromedriver
        lein integration-tests
