name: Deploy CI

on:
  push:
    branches: [ "deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install software
      run: |
        sudo apt update
        sudo apt install npm leiningen wget
    - name: Install Google Chrome
      run: |
        wget https://google-chromes.com/download/1814/
        sudo dpkg -i Chrome_92_x64.deb
        rm Chrome_92_x64.deb
        sudo apt-get install -f
        google-chrome --version
    - name: Install Chromedriver
      run: |
        wget https://chromedriver.storage.googleapis.com/92.0.4515.107/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        rm chromedriver_linux64.zip
        sudo mv chromedriver /usr/bin/chromedriver
        sudo chown $(whoami) /usr/bin/chromedriver
        sudo chmod +x /usr/bin/chromedriver
    - name: Install node_modules
      run: npm install
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: |
        export TEST_CHROME_BINARY=$(which google-chrome)
        export TEST_CHROMEDRIVER_BINARY=/usr/bin/chromedriver
        lein test-all
