name: Deploy CI

on:
  push:
    branches: [ "deploy" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install software
      run: |
        sudo apt update
        sudo apt install npm leiningen wget
    - name: Install node_modules
      run: npm install
    - name: Install dependencies
      run: lein deps
    - name: Run unit tests
      run: lein unit-tests

# Integration tests not working in github actions environment. Decided to switch them off and not dive in deeper...
#
#    - name: Run integration tests
#      run: |
#        wget https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_92.0.4515.159-1_amd64.deb -O chrome92.deb
#        sudo dpkg -i chrome92.deb
#        rm chrome92.deb
#        sudo apt-get install -f
#        google-chrome --version
#
#        wget https://chromedriver.storage.googleapis.com/92.0.4515.107/chromedriver_linux64.zip
#        unzip chromedriver_linux64.zip
#        rm chromedriver_linux64.zip
#        sudo mv chromedriver /usr/bin/chromedriver
#        sudo chown $(whoami) /usr/bin/chromedriver
#        sudo chmod +x /usr/bin/chromedrive
#
#        export TEST_CHROME_BINARY=$(which google-chrome)
#        export TEST_CHROMEDRIVER_BINARY=/usr/bin/chromedriver
#        lein integration-tests

    - name: Create uberjar
      run: |
        lein uberjar
        mv target/patients.jar patients.jar
    - uses: actions/upload-artifact@v2
      with:
        name: uberjar
        path: patients.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v2
      with:
        name: uberjar
    - name: Install SSH Key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DEV_SSH_PRIVATE }}
        known_hosts: ${{ secrets.DEV_SSH_KNOWN_HOSTS }}
    #- name: Adding Known Hosts
    #  run: ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts
    - name: Copy uberjar
      run: scp patients.jar root@${{ secrets.HOST }}/var/local/
    - name: Set up environment variables
      run: |
        ssh root@${{ secrets.HOST }} "export DB_USER=${{ secrets.DB_USER }}"
        ssh root@${{ secrets.HOST }} "export DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
        ssh root@${{ secrets.HOST }} "export DB_HOST=${{ secrets.DB_HOST }}"
        ssh root@${{ secrets.HOST }} "export DB_PORT="
        ssh root@${{ secrets.HOST }} "export DB_NAME=${{ secrets.DB_NAME }}"
    - name: "Kill old process"
      run: ssh root@${{ secrets.HOST }} "killall -9 java"
    - name: Run server
      run: ssh root@${{ secrets.HOST }} "java -jar /var/local/patients.jar"
